// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TermProjectX.Models;

namespace TermProjectX.Migrations
{
    [DbContext(typeof(SCPContext))]
    [Migration("20221209044149_descriptionOC")]
    partial class descriptionOC
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TermProjectX.Models.ObjectClass", b =>
                {
                    b.Property<int>("ObjectClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(1500)")
                        .HasMaxLength(1500);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ObjectClassId");

                    b.ToTable("ObjectClasses");

                    b.HasData(
                        new
                        {
                            ObjectClassId = -1,
                            Description = "Safe-class SCPs are anomalies that are easily and safely contained. This is often due to the fact that the Foundation has researched the SCP well enough that containment does not require significant resources or that the anomalies require a specific and conscious activation or trigger. Classifying an SCP as Safe, however, does not mean that handling or activating it does not pose a threat.",
                            Name = "Safe"
                        },
                        new
                        {
                            ObjectClassId = -2,
                            Description = "Euclid-class SCPs are anomalies that require more resources to contain completely or where containment isn't always reliable. Usually this is because the SCP is insufficiently understood or inherently unpredictable. Euclid is the Object Class with the greatest scope, and it's usually a safe bet that an SCP will be this class if it doesn't easily fall into any of the other standard Object Classes.",
                            Name = "Euclid"
                        });
                });

            modelBuilder.Entity("TermProjectX.Models.SCP", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Containment")
                        .IsRequired()
                        .HasColumnType("nvarchar(1500)")
                        .HasMaxLength(1500);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(1500)")
                        .HasMaxLength(1500);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<int>("ObjectClassID")
                        .HasColumnType("int");

                    b.Property<int>("ThreatLevelID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ObjectClassID");

                    b.HasIndex("ThreatLevelID");

                    b.ToTable("SCPs");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Containment = "Standard human containment cell",
                            Description = "SCP-5881 refers to Ben Hennessy, a 26 year old British male, who subconsciously manifests three Class 2 incorporeal entities that resemble different versions of himself. These instances manifest around SCP-5881 and converse with him for any amount of time between 2 minutes to 5 hours. These conversations involve SCP-5881 being instructed on a variety of subjects, including mathematics, computer science, ancient and modern history, science, physical education and various life and social skills. SCP-5881 manifestations previously occurred a minimum of once every two hours, and a maximum of once every three days. Only one instance can manifest at a time.",
                            Name = "SCP-5581",
                            ObjectClassID = -1,
                            ThreatLevelID = -1
                        },
                        new
                        {
                            ID = 2,
                            Containment = "Wooden Pigeon Coop",
                            Description = "Roughly 39cm in length and 34cm in height. Despite lacking the proper bodily structures for human speech, SCP-6567 is a proficient speaker of both the English and Italian languages. SCP-6567 refers to itself as 'Eduardo Uccello, ' a self proclaimed, former Italian-American mafia underboss. Despite inhibiting the entity's ability to fly, the entity always adorns a pigeon tailored Armani blue-gray striped suit and tie as well as a dark gray fedora while outside of its enclosure. When asked how it acquired such apparel, SCP-6567 explained that it was,  'A gift from some of my subordinates. '",
                            Name = "SCP-6567",
                            ObjectClassID = -2,
                            ThreatLevelID = -2
                        },
                        new
                        {
                            ID = 3,
                            Containment = "Fencing",
                            Description = "SCP-1271 is a square tract of land approximately 20 m on each side, roughly landscaped into a functional kickball field. The field comprised a portion of the grounds of Sheckler Elementary School in Catasauqua, PA, before the school was closed in 1967. The grounds have been abandoned ever since.",
                            Name = "SPC-1271",
                            ObjectClassID = -1,
                            ThreatLevelID = -1
                        },
                        new
                        {
                            ID = 4,
                            Containment = "Cryo-containment Facility",
                            Description = "SCP-189 is a species of parasitic roundworm (tentative taxonomic classification [DATA EXPUNGED]) capable of infesting any mammalian life form. Infection most commonly occurs as a result of direct skin contact with one or more egg sacs. These egg sacs are covered with microscopic \"hooks\" similar to those on the cuticles of some species of nematode, which anchor the sacs to the skin's surface. Contact with sebum then prompts the eggs inside to hatch, at which time the larvae seek out and burrow into one or more nearby hair follicles.",
                            Name = "SCP-189",
                            ObjectClassID = -2,
                            ThreatLevelID = -2
                        });
                });

            modelBuilder.Entity("TermProjectX.Models.ThreatLevel", b =>
                {
                    b.Property<int>("ThreatLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ThreatLevelId");

                    b.ToTable("ThreatLevels");

                    b.HasData(
                        new
                        {
                            ThreatLevelId = -1,
                            Name = "Green"
                        },
                        new
                        {
                            ThreatLevelId = -2,
                            Name = "Blue"
                        });
                });

            modelBuilder.Entity("TermProjectX.Models.SCP", b =>
                {
                    b.HasOne("TermProjectX.Models.ObjectClass", "ObjectClass")
                        .WithMany()
                        .HasForeignKey("ObjectClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TermProjectX.Models.ThreatLevel", "ThreatLevel")
                        .WithMany()
                        .HasForeignKey("ThreatLevelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
